//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuckZuck_Tool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RuckZuck_Tool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System.Runtime.InteropServices;
        ///
        ///[assembly: AssemblyTitle(&quot;RuckZuck Package-Wrapper&quot;)]
        ///[assembly: AssemblyDescription(&quot;Install Software from the RuckZuck.tools Repository&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&quot;)]
        ///[assembly: AssemblyCompany(&quot;RuckZuck.tools&quot;)]
        ///[assembly: AssemblyProduct(&quot;RZRZRZ&quot;)]
        ///[assembly: AssemblyCopyright(&quot;Copyright ©  2016 by Roger Zander&quot;)]
        ///[assembly: AssemblyTrademark(&quot;&quot;)]
        ///[assembly: AssemblyCulture(&quot;&quot;)]
        ///[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Net;
        ///using System.IO;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Runtime.Serialization;
        ///using System.Linq;
        ///
        ///namespace RuckZuck_WCF
        ///{
        ///    class RZRestAPI
        ///    {
        ///        public static string sURL = &quot;http://ruckzuck.azurewebsites.net/wcf/RZService.svc&quot;;
        ///        //internal static string sURL = &quot;http://localhost:7727/RZService.svc&quot;;
        ///
        ///        public static string Token;
        ///        public static string GetAuthToken(string  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RZRestApi {
            get {
                return ResourceManager.GetString("RZRestApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///using System.Net;
        ///using System.IO;
        ///using System.Management.Automation;
        ///using System.Collections.ObjectModel;
        ///using System.Threading.Tasks;
        ///using System.Xml;
        ///using RuckZuck_WCF;
        ///using System.Security.Cryptography.X509Certificates;
        ///using System.Threading;
        ///using System.Xml.Linq;
        ///
        ///namespace RZUpdate
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Updater Class
        ///    /// &lt;/summary&gt;
        ///    public class RZUpdater
        ///    {
        ///
        ///        static string sAuthTo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RZUpdate {
            get {
                return ResourceManager.GetString("RZUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using RZUpdate;
        ///using System;
        ///using System.IO;
        ///using System.IO.Compression;
        ///using System.Reflection;
        ///using System.Resources;
        ///using System.Text;
        ///using System.Threading;
        ///
        ///namespace RZWrapper
        ///{
        ///    class RZWrapperClass
        ///    {
        ///        static int Main(string[] args)
        ///        {
        ///            Mutex mutex = new Mutex(false, &quot;RuckZuck&quot;);
        ///            try
        ///            {
        ///                string xmlSW = null;
        ///                //var xmlSW = Unzip(oOut);
        ///
        ///                try
        ///                {
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
    }
}
