//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuckZuck_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public long Id { get; set; }
        public long DeploymentTypeID { get; set; }
        public string DownloadURL { get; set; }
        public string Filename { get; set; }
        public string FileHash { get; set; }
        public string HashType { get; set; }
    
        public virtual DeploymentType DeploymentType { get; set; }
    }
}
