//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuckZuck_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeploymentType
    {
        public DeploymentType()
        {
            this.Content = new HashSet<Content>();
        }
    
        public long Id { get; set; }
        public long ProductVersionId { get; set; }
        public string Type { get; set; }
        public string PSPreReq { get; set; }
        public string PSPreInstall { get; set; }
        public string PSInstall { get; set; }
        public string PSPostInstall { get; set; }
        public string PSUninstall { get; set; }
        public string PSDetection { get; set; }
        public Nullable<System.Guid> ContentID { get; set; }
        public Nullable<bool> IsSealed { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public string Author { get; set; }
    
        public virtual ICollection<Content> Content { get; set; }
        public virtual ProductVersion ProductVersion { get; set; }
    }
}
