//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuckZuck_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPFSMap
    {
        public string ContentID { get; set; }
        public string IPFS { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<long> Size { get; set; }
    }
}
