//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuckZuck_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVersion
    {
        public ProductVersion()
        {
            this.DeploymentType = new HashSet<DeploymentType>();
            this.WindowsInstallerIDs = new HashSet<WindowsInstallerIDs>();
        }
    
        public long Id { get; set; }
        public long ProductId { get; set; }
        public byte[] Icon { get; set; }
        public string Version { get; set; }
        public Nullable<bool> IsLatest { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    
        public virtual ICollection<DeploymentType> DeploymentType { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<WindowsInstallerIDs> WindowsInstallerIDs { get; set; }
    }
}
