//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuckZuck_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVersionDownloads
    {
        public long Id { get; set; }
        public long ProductVersionId { get; set; }
        public System.DateTime DownloadDateTime { get; set; }
        public long InstallTypeId { get; set; }
    }
}
