//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuckZuck_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductVersion = new HashSet<ProductVersion>();
        }
    
        public long Id { get; set; }
        public string ProductName { get; set; }
        public string Manufacturer { get; set; }
        public string ProductDescription { get; set; }
        public string ShortName { get; set; }
        public string ProjectURL { get; set; }
    
        public virtual ICollection<ProductVersion> ProductVersion { get; set; }
    }
}
