//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuckZuck_WCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SWEntitiesApi : DbContext
    {
        public SWEntitiesApi()
            : base("name=SWEntitiesApi")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SWVersions> SWVersions { get; set; }
        public DbSet<SWDetails> SWDetails { get; set; }
        public DbSet<v_SWVersions> v_SWVersions { get; set; }
        public DbSet<v_SWVersionsLatest> v_SWVersionsLatest { get; set; }
        public DbSet<v_SWDetails> v_SWDetails { get; set; }
        public DbSet<SWFeedback> SWFeedback { get; set; }
        public DbSet<SWPending> SWPending { get; set; }
        public DbSet<v_SWVersionsOLD> v_SWVersionsOLD { get; set; }
        public DbSet<IPFSMap> IPFSMap { get; set; }
    }
}
