//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuckZuck_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWPending
    {
        public long Id { get; set; }
        public long SWId { get; set; }
        public string ProductName { get; set; }
        public string Architecture { get; set; }
        public string Username { get; set; }
    }
}
