//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuckZuck_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFeedbackSuccessRatio
    {
        public long ProductVersionId { get; set; }
        public Nullable<int> Success { get; set; }
        public Nullable<int> Failed { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> SuccessRatio { get; set; }
        public Nullable<System.DateTime> LastStatus { get; set; }
    }
}
