//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuckZuck_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPreRequisites
    {
        public string ProductName { get; set; }
        public string ShortName { get; set; }
        public int Position { get; set; }
        public string DepProdName { get; set; }
        public string DepProdversion { get; set; }
        public bool Enabled { get; set; }
    }
}
