//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuckZuck_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProductsWithIssues
    {
        public string ShortName { get; set; }
        public string ProductName { get; set; }
        public string Version { get; set; }
        public long ProductVersionId { get; set; }
        public bool Working { get; set; }
        public string UserKey { get; set; }
        public string Feedback { get; set; }
        public System.DateTime CreationDateTime { get; set; }
    }
}
